### PR TITLE
Azure storage naming fix

### PR DESCRIPTION
**Pull request by ghost**
Also fixed a typo and removed unused method parameters

### CODE REVIEW

**Comment by ghost** [comment]
Add parameters when we need them not before. (YAGNI)

**Comment by scotmoor** [comment]
YAGNI?

LGTM

**Comment by scotmoor** [comment]
Ah crap.....I hit the wrong button

**Comment by scotmoor** [comment]
LGTM

**Comment by ghost** [comment]
https://en.m.wikipedia.org/wiki/You_aren%27t_gonna_need_it

Sent from my Windows Phone

**Pull request closed without merging**
