### PR TITLE
Add server group name versioning and remove obsolete UpsertAzureLoadB…

### PR DESCRIPTION
**Pull request by milismsft**
…alancerDescription class

### CODE REVIEW

**Comment by milismsft** [comment]
@JargoonPard @scotmoor PTAL

**Comment by ghost** [comment]
LGTM

**Comment by scotmoor** [comment]
We should create a task to also clean up the UpsertAzureSecurityGroupDescription as well.

Other than that, LGTM

**Comment by milismsft** [comment]
@JargoonPard @scotmoor I had to push couple small changes from the PR you guys looked at first.

**Pull request closed without merging**
